### ISSUE TITLE
Chunks don't start generating unless the generation source is moved

### ISSUE THREAD

**Issue by BLaZeKiLL** [runevision/LayerProcGen#20] opened 2024-12-07 05:29 UTC
First of all thanks for making this, have been stuck on making something like this for a while

I noticed that chunks don't start generating unless the generation source starts moving, so unless the player moves a bit the world would be empty, not sure if this is the expected behaviour but is there a way to generate the initial chunks around the generation source without the movement being required ?

https://github.com/user-attachments/assets/8e3344c5-efe9-4772-b589-e0de2f9c9b4d

Using the simple sample scene in a blank HDRP project

**Comment by BLaZeKiLL** [comment] 2024-12-07 05:49
So this only happens if GenerationSource is at 0,0,0 initially, doesn't trigger the generation of chunks as it's same as focus of the top level dependency as the focus point is initialized to (0, 0).

2 work around, don't have generation source at 0,0,0 or change the initial focus of the top level dependency when it's created to some other value

```cs
// Create top layer dependency based on layer.
if (instance != null && (dep == null || dep.layer != instance)) {
  if (dep != null)
	  dep.isActive = false;
  dep = new TopLayerDependency(instance, size);
  dep.SetFocus(new Point(-100, -100)); // best would be -inf, -inf
}
```

**Comment by runevision** [comment] 2024-12-07 12:17
Thanks for making me aware of this!

This seems to be a regression introduced in version 0.2.0 as it works fine in version 0.1.0. I'm looking into it.

**Comment by runevision** [comment] 2024-12-07 13:06
Fixed in commit https://github.com/runevision/LayerProcGen/commit/6c2e079af8c0e44d4350af2b17a80ec2b9c2b62a

**Closed** 2024-12-07 13:05 UTC
